In [29]:
import numpy as np

# The Basics of NumPy Arrays - manipulations 


*  **Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays
*  **Indexing of arrays**: Getting and setting the value of individual array elements
*  **Slicing of arrays**: Getting and setting smaller subarrays within a larger array
*  **Reshaping of arrays**: Changing the shape of a given array
*  **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many

## Accessing Array Attributes

In [ ]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("single dimentional array", x1)
print ("2 Dimentional array: ", x2)

print("3  dimentional arrayc", x3)

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), size (the total size of the array) and the data type of the array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)

To get item size of each element in bytes and total size of array

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

In [ ]:
'''arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
print(arr[arr % 2 == 1])'''


## Array Indexing: Accessing Single Elements

**randint syntax**

np.random.randint(low, high, size, datatype )

low - lowest possible value.
high - upperbound value.. but excluded 

In [30]:

np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [ ]:
x1

In [ ]:
x1[0]

In [ ]:
x1[4]

To index from the end of the array, you can use negative indices:

In [ ]:
x1[-1]

In [ ]:
x1[-2]

In a multi-dimensional array, items can be accessed using a **comma-separated tuple of indices**:

**mat[row, col]
mat[row][col]**

In [ ]:
x2

In [ ]:
x2[1, 3]

In [ ]:
x2[2][3]

In [ ]:
x2[2,3]

In [ ]:
x2[2, 0]

In [ ]:
x2[2, -1]

**Values can also be modified** using any of the above index notation:

In [ ]:
x2[0, 0] = 12
x2

## Array Slicing: Accessing Subarrays


The **NumPy slicing syntax follows that of the standard Python list**; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

In [ ]:
x[:5]  # first five elements

In [ ]:
x[4:7]  # middle sub-array

In [ ]:
swap = np.array([[1,2,3],[4,5,6],[7,8,9]])
#swap[:,::-1]
#print(swap[::-1])
swap

In [ ]:
swap[:,::-1]

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [ ]:
x2

In [ ]:
x2[:,-1]

In [ ]:
x2[:,3]

In [ ]:
x2[:2, :3]  # two rows, three columns

In [ ]:
x2[:3, ::2]  # all rows, every other column

### Subarrays as no-copy views

Note **array slices  return *views* rather than *copies* of the array data**
This is one area in which NumPy array slicing differs from Python list slicing: **in lists, slices will be copies.**
Consider our two-dimensional array from before:

In [31]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Let's extract a $2 \times 2$ subarray from this:

In [32]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


Now if we **modify this subarray**, we'll see that the **original array is changed!** Observe:

In [33]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This is  **quite usefu**l: **it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.**

### Creating copies of arrays

For getting copy explicitely use  ``copy()`` method:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

If we now modify this subarray, the original array is not touched:

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

In [ ]:
print(x2)

## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [ ]:
grid = np.arange(1, 11).reshape((2, 5))
print(grid)

Note that for this to work, **the size of the initial array must match the size of the reshaped array.** 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [ ]:
grid.reshape(5,2)

In [35]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

## Array Concatenation and Splitting

It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. 

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines **``np.concatenate``, ``np.vstack``, and ``np.hstack``**.
**``np.concatenate`` takes a tuple or list of arrays as its first argument**, as we can see here:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

It can also be used for two-dimensional arrays:

In [36]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [41]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [42]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, ``np.dstack`` will stack arrays along the third axis.

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [43]:
a = np.arange(9) 

print ('First array:') 
print (a) 
print ('\n')  

print ('Split the array in 3 equal-sized subarrays:') 
b = np.split(a,3) 
print (b) 
print ('\n')  

print ('Split the array at positions indicated in 1-D array:') #i.e. 4th place and at 7th place
b = np.split(a,[4,7])
print (b)

First array:
[0 1 2 3 4 5 6 7 8]


Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [44]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [45]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
upper, lower = np.vsplit(grid, [3])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [3])
print(left)
print(right)

Similarly, ``np.dsplit`` will split arrays along the third axis.