## Ufuncs: Index Preservation

In [2]:
import pandas as pd
import numpy as np

In [5]:
#Ufuncs preserve indexes after performing operations on padas objects
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
print(ser)

0    6
1    3
2    7
3    4
dtype: int64


In [ ]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [6]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
print(df)

   A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4


In [ ]:
np.sin(df * np.pi / 4)

## Index alignment in Series

In [ ]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
print(area)
print(population)

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64
California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64


In [ ]:
print(population)

In [ ]:
a = population / area
a

#NaN is introduced for missing index values

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

## Indices handling missing values 

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print(A)
print(B)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64


In [ ]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [ ]:
# Incase of missing value, fill_value can be used to perform default operation
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

## Index alignment in DataFrame

In [ ]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list('AB'))
B = pd.DataFrame(rng.randint(0, 10, (3, 3)), columns=list('BAC'))

print(B)


   B  A  C
0  7  4  3
1  7  7  2
2  5  4  1


In [ ]:
print(A)

    A   B
0   6  18
1  10  10


In [ ]:
A+B
# Irrespective of order of columns, they are matched and + operation is performed

A     B   C
0  10.0  25.0 NaN
1  17.0  17.0 NaN
2   NaN   NaN NaN

In [ ]:
A.add(B, fill_value=0)

In [ ]:
#rather than default fill = 0, populate mean of A and fill
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0  10.0  25.0  14.0
1  17.0  17.0  13.0
2  15.0  16.0  12.0

In [ ]:
fill

11.0

## Ufuncs: Operations Between DataFrame and Series

In [ ]:
#the index and column alignment is maintained while performingn operation between 2D and 1D array
A = rng.randint(10, size=(3, 4))
A

array([[7, 5, 1, 4],
       [0, 9, 5, 8],
       [0, 9, 2, 6]])

In [ ]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-7,  4,  4,  4],
       [-7,  4,  1,  2]])

In [ ]:
B = [1,7,5,1]
A - B

array([[ 6, -2, -4,  3],
       [-1,  2,  0,  7],
       [-1,  2, -3,  5]])

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  7  5  1  4
1  0  9  5  8
2  0  9  2  6

In [ ]:
df - df.iloc[0]

In [ ]:
df.iloc[0]  #0th row
print(df)


In [ ]:
# Specfying column level operations
# use Object methods
df.subtract(df['R'], axis=0)

Q  R  S  T
0  2  0 -4 -1
1 -9  0 -4 -1
2 -9  0 -7 -3

In [ ]:
halfrow = df.iloc[0, ::2]
halfrow

Q    7
S    1
Name: 0, dtype: int64

In [ ]:
df - halfrow