In [1]:
# Q1 Create a 3×3 numpy array of all True’s 

In [9]:
import numpy as np
x=np.arange(9).reshape(3,3)

In [12]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
np.full((3, 3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [17]:
# Q2 Extract all odd numbers from arrays 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [19]:
# Q3 Replace all even numbers in above array with -5 

In [62]:
arr[arr%2==0]= -5
arr

array([-5,  1, -5,  3, -5,  5, -5,  7, -5,  9])

In [27]:
# Q4 Reshape an array 

a=np.array([0,1,2,3,4,5,6,7,8,9])
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
# Q5 How to get the positions where elements of two arrays match 

a = np.array([1,2,3,2,3,4,3,4,5,6])
print(a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [39]:
np.where(np.equal(a,b))

(array([1, 3, 5, 7], dtype=int64),)

In [53]:
# Q6 Swap columns 1 and 2 in the array 

s1=np.array([[1,2,3],[4,5,6],[7,8,9]])
'''s1[:, [1,0]]= s1[:,[0,1]]
print(s1)'''
s1[:,::-1]


array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [55]:
# Q7 Reversing the columns of a 2D array 

rev=np.array([[1,2,3],[4,5,6],[7,8,9]])
rev


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
# reversing column order in matrix
flipped_arr = np.fliplr(rev)
print("Reversing the columns",flipped_arr)

Reversing the columns [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [58]:
# Q8 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10 

In [66]:
arr=np.arange(9).reshape(3,3)
x1=np.random.uniform(5,10,size=(5,3))# 2D Array
print(x1)

[[7.70587183 7.84840555 6.30370959]
 [5.9880059  7.08671926 8.88991724]
 [7.49945281 5.68842961 8.15223174]
 [8.8822173  8.2333568  6.45578564]
 [7.14391145 7.03576883 7.62166338]]


In [67]:
# Q9 Create a 2d array with 1 on the border and 0 inside 

In [68]:
x=np.ones((5,5))
print("Original array",x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
# Q10 If 
# Write script to produce the desired output. Use of fancy indexing is must.  
x=np.array([[9,1,12,3],[14,15,6,7],[18,9,10,11]])
x
row=np.array([0,1,2])
col=np.array([2,0,3])
x[row,col]


array([12, 14, 11])